# è®¢é˜…åœ°å€
p: &p
  {type: http, url: "å¼•å·å†…å¡«å†™ä½ çš„è®¢é˜…åœ°å€", interval: 21600, health-check: {enable: true, url: https://www.google.com/generate_204, interval: 300}}


# by LIghtJUNction
# ç¬¬ä¸€éƒ¨åˆ† å¿«é€Ÿé…ç½®

# é…ç½®ç»„ä¸€             ç«¯å£ç±»
mixed-port: 7890
redir-port: 7891
tproxy-port: 1536

# å¤–éƒ¨æ§åˆ¶ (API)
external-controller: 127.0.0.1:9090 # å¤–éƒ¨æ§åˆ¶å™¨ï¼Œå¯ä»¥ä½¿ç”¨ RESTful API æ¥æ§åˆ¶ä½ çš„ Clash å†…æ ¸ï¼›API ç›‘å¬åœ°å€ï¼Œä½ å¯ä»¥å°† 127.0.0.1 ä¿®æ”¹ä¸º 0.0.0.0 æ¥ç›‘å¬æ‰€æœ‰ IPï¼›è®¿é—®åœ°å€ï¼šhttp://127.0.0.1:9090
secret: "" # API çš„è®¿é—®å¯†é’¥ é»˜è®¤ä¸æ·»åŠ 
#é¢æ¿é»˜è®¤Yacd å¯é€‰Meta æ¸…é™¤æµè§ˆå™¨ç¼“å­˜å³å¯é‡æ–°åŠ è½½
external-ui: /data/adb/Box/panel/Yacd/ #/Meta #/Yacd
# external-ui-name: "lightjunction" # è‡ªå®šä¹‰å¤–éƒ¨ç”¨æˆ·ç•Œé¢åå­—




# é…ç½®ç»„äºŒ            å¸ƒå°”ç±»
ipv6: false
allow-lan: true
tcp-concurrent: true
unified-delay: true
geodata-mode: true # æ˜¯å¦å¯ç”¨ geodata è§„åˆ™é›†å’Œgeodataéƒ½å¯ç”¨
geo-auto-update: true # æ˜¯å¦è‡ªåŠ¨æ›´æ–° geodata
geo-update-interval: 24 # æ›´æ–°é—´éš”ï¼Œå•ä½ï¼šå°æ—¶
keep-alive-interval: 1800  # å‡å°‘ç§»åŠ¨ç«¯è®¾å¤‡è€—ç”µ

# é…ç½®ç»„ä¸‰           é€‰æ‹©ç±»
mode: rule  # ruleï¼ˆé»˜è®¤ï¼‰ globalï¼ˆéœ€è¦åœ¨GLOBALç­–ç•¥ç»„é€‰æ‹©ï¼‰direct 
log-level: silent
global-client-fingerprint: random # éšæœºæŒ‡çº¹ ï¼ˆå…¨å±€å®¢æˆ·ç«¯æŒ‡çº¹ï¼‰
geodata-loader: memconservative # memconservativeï¼ˆå°å†…å­˜ï¼‰ standard
find-process-mode: strict


      
hosts:
  time.facebook.com: 17.253.84.125
  time.android.com: 17.253.84.125
  '*.mihomo.dev': 127.0.0.1
  '.dev': 127.0.0.1
  'alpha.mihomo.dev': '::1'
  test.com: [1.1.1.1, 2.2.2.2]
  home.lan: lan # lan ä¸ºç‰¹åˆ«å­—æ®µï¼Œå°†åŠ å…¥æœ¬åœ°æ‰€æœ‰ç½‘å¡çš„åœ°å€
  # åªå…è®¸é…ç½®ä¸€ä¸ªåˆ«å


# é…ç½®ç»„-é«˜çº§

dns:   # DNSæ³„éœ²é—®é¢˜ 
  cache-algorithm: arc # ARCï¼ˆAdaptive Replacement Cacheï¼‰ç¼“å­˜ç®—æ³•
  enable: true  # ä½¿ç”¨clashDNS
  listen: 0.0.0.0:1053
  use-hosts: true
  ipv6: true
  ipv6-timeout: 300  # å•ä½ï¼šmsï¼Œå†…éƒ¨åŒæ ˆå¹¶å‘æ—¶ï¼Œå‘ä¸Šæ¸¸æŸ¥è¯¢ AAAA æ—¶ï¼Œç­‰å¾… AAAA çš„æ—¶é—´ï¼Œé»˜è®¤ 100ms
  prefer-h3: true # æ˜¯å¦å¼€å¯ DOH çš„ http/3ã€‚ 
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
    - '+.leigod.com'
    - '+.vivox.com'
    - '+.stun.+'
    - '.n.n.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.*.microsoft.com'
    - '*.*.xboxlive.com'
    - 'lens.l.google.com'
    - '*.mcdn.bilivideo.cn'
    - "connect.rom.miui.com"
    - 'localhost.ptlogin2.qq.com'
    - 'weatherapi.market.xiaomi.com'
    - WORKGROUP
    

# åªèƒ½ä½¿ç”¨çº¯ IP åœ°å€ï¼Œå¯ä½¿ç”¨åŠ å¯† DNS æƒ³è¦DNSä¸æ³„éœ²å°±ç”¨åŠ å¯†DNS
  nameserver:    # ä¸»è¦ å›½å†…ä»£ç†
    - https://1.1.1.1/dns-queryğŸš€ èŠ‚ç‚¹é€‰æ‹©
    - https://1.0.0.1/dns-queryğŸš€ èŠ‚ç‚¹é€‰æ‹©
    - tls://223.5.5.5:853#ğŸš€ èŠ‚ç‚¹é€‰æ‹© # DNS over TLS
    - https://doh.pub/dns-query#ğŸš€ èŠ‚ç‚¹é€‰æ‹© # DNS over HTTPS
    - https://mozilla.cloudflare-dns.com/dns-query#ğŸš€ èŠ‚ç‚¹é€‰æ‹©&h3=true # æŒ‡å®šç­–ç•¥ç»„å’Œä½¿ç”¨ HTTP/3
    - dhcp://en0ğŸš€ èŠ‚ç‚¹é€‰æ‹©  # dns from dhcp #æµ‹è¯•

  # åªèƒ½ä½¿ç”¨çº¯ IP åœ°å€ï¼Œå¯ä½¿ç”¨åŠ å¯† DNS
  default-nameserver: 
    - tls://1.12.12.12:853
    - tls://223.5.5.5:853
    - https://223.5.5.5/dns-query 
    - tcp://119.29.29.29
    - tcp://223.6.6.6 
    - system 
    
  nameserver-policy:
    "geosite:cn,private":
      - https://223.5.5.5/dns-query
      - https://doh.pub/dns-query
      - https://doh.360.cn/dns-query
      - tls://223.5.5.5
      - tls://dot.pub
    "rule-set:direct,private,apple,icloud":
      - https://223.5.5.5/dns-query
      - https://doh.pub/dns-query
      - https://doh.360.cn/dns-query
      - tls://223.5.5.5
      - tls://dot.pub         

  proxy-server-nameserver:
  #  - https://223.5.5.5/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
    - tls://223.5.5.5
    - tls://dot.pub     
    
  fallback:
    - quic://a.passcloud.xyz:784ğŸš€ èŠ‚ç‚¹é€‰æ‹© # quicæ˜¯æ–°å…´çš„ï¼Œæ¯”tlså¿«ä¸€å€
    - tls://8.8.4.4:853ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    - tcp://1.1.1.1ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    - https://1.1.1.1/dns-queryğŸš€ èŠ‚ç‚¹é€‰æ‹©&h3=true
    - https://1.0.0.1/dns-queryğŸš€ èŠ‚ç‚¹é€‰æ‹©
    - tls://1dot1dot1dot1.cloudflare-dns.comğŸš€ èŠ‚ç‚¹é€‰æ‹© 

  fallback-filter:    # å›½å¤–ç½‘ç«™ä½¿ç”¨æ­¤è§£æ
    geoip: true # é…ç½®æ˜¯å¦ä½¿ç”¨ geoip
    geoip-code: CN
    geosite:      # æ ¹æ®å®é™…æƒ…å†µå†³å®š
      - cn
      - games-cn
      - apple-cn
      - microsoft-cn 
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
      - '+.googleapis.+'     
# DNSé…ç½®å®Œæˆ


# æ¨¡å¼é…ç½®
tun:    # tunæ¨¡å¼
  enable: true
  device: utun # gvisor/mixed
  mtu: 9000 # æœ€å¤§ä¼ è¾“å•å…ƒ
  stack: system # gvisor / lwip / system
  dns-hijack: # dns åŠ«æŒï¼Œå°†åŒ¹é…åˆ°çš„è¿æ¥å¯¼å…¥å†…éƒ¨ dns æ¨¡å—ï¼Œä¸ä¹¦å†™åè®®åˆ™ä¸º udp://
    - udp://any:53  # éœ€è¦åŠ«æŒçš„ DNS
    - tcp://any:53
  auto-route: true # é…ç½®è·¯ç”±è¡¨
  auto-detect-interface: true  # è‡ªåŠ¨è¯†åˆ«å‡ºå£ç½‘å¡
  endpoint-independent-nat: false # å¯ç”¨ç‹¬ç«‹äºç«¯ç‚¹çš„ NAT,æ€§èƒ½å¯èƒ½ä¼šç•¥æœ‰ä¸‹é™,æ‰€ä»¥å»ºè®®åœ¨éœ€è¦çš„æ—¶å€™å¼€å¯
  inet4-route-exclude-address: #å¯ç”¨ auto-route æ—¶æ’é™¤è‡ªå®šä¹‰ç½‘æ®µ
    - 192.168.0.0/16
  inet6-route-exclude-address: #å¯ç”¨ auto-route æ—¶æ’é™¤è‡ªå®šä¹‰ç½‘æ®µ
    - fc00::/7
  inet4-route-address: # å¯ç”¨ auto-route æ—¶ä½¿ç”¨è‡ªå®šä¹‰è·¯ç”±è€Œä¸æ˜¯é»˜è®¤è·¯ç”±
    - 0.0.0.0/1
    - 128.0.0.0/1
  inet6-route-address: # å¯ç”¨ auto-route æ—¶ä½¿ç”¨è‡ªå®šä¹‰è·¯ç”±è€Œä¸æ˜¯é»˜è®¤è·¯ç”±
    - "::/1"
    - "8000::/1"
   # strict-route: true # å°†æ‰€æœ‰è¿æ¥è·¯ç”±åˆ° tun æ¥é˜²æ­¢æ³„æ¼ï¼Œä½†ä½ çš„è®¾å¤‡å°†æ— æ³•å…¶ä»–è®¾å¤‡è¢«è®¿é—® çƒ­ç‚¹å°†æ— æ³•å…±äº«ç½‘ç»œ
  include_android_user:
    - 0
    # å¤šå¼€ç”¨æˆ·
   #  include_package:
   #    - com.android.chrome
  # exclude_package:
    # - com.tencent.mm #  æ²¡å¿…è¦å¼€


sniffer:      # mihomoçš„åŸŸåå—…æ¢åŠŸèƒ½ å¦‚æœä¸ä½¿ç”¨Clashå†…ç½®çš„DNSè§£ææœåŠ¡ï¼Œå°±æ— æ³•å‡†ç¡®è¿˜åŸåŸŸåï¼Œè¿›è¡ŒåŸŸååˆ†æµ             
  enable: true                    
  force-dns-mapping: true
  parse-pure-ip: true          
  override-destination: true      
  sniff:   # TLS å’Œ QUIC é»˜è®¤å¦‚æœä¸é…ç½® ports é»˜è®¤å—…æ¢ 443
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
    HTTP: # éœ€è¦å—…æ¢çš„ç«¯å£, é»˜è®¤å—…æ¢ 80
      ports: [80, 8080-8880]
      override-destination: true # å¯è¦†ç›– sniffer.override-destination
  force-domain:
    - google.com
    - +.v2ex.com
  # # ç™½åå•,è·³è¿‡å—…æ¢ç»“æœ
  skip-domain:
    - Mijia Cloud
    - +.apple.com
  sniffing:
    - tls
    - http
  port-whitelist:
    - "80"
    - "443"

profile:
  store-selected: true
  # å‚¨å­˜ API å¯¹ç­–ç•¥ç»„çš„é€‰æ‹©ï¼Œä»¥ä¾›ä¸‹æ¬¡å¯åŠ¨æ—¶ä½¿ç”¨
  store-fake-ip: true
  # å‚¨å­˜ fakeip æ˜ å°„è¡¨ï¼ŒåŸŸåå†æ¬¡å‘ç”Ÿè¿æ¥æ—¶ï¼Œä½¿ç”¨åŸæœ‰æ˜ å°„åœ°å€


# https://github.com/Loyalsoldier/v2ray-rules-dat çš„å¤åˆ» https://github.com/DustinWin/ruleset_geodata 
geox-url:
  geoip: "https://mirror.ghproxy.com/https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo/geoip.dat"
  geosite: "https://mirror.ghproxy.com/https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo/geosite.dat"
  

# ç¬¬äºŒéƒ¨åˆ† ä»£ç†ç»„é…ç½®  
proxy-providers:
  sub:
    <<: *p
    path: ./proxy_providers/sub.yaml
proxies:
  - {name: ğŸŒ å…¨çƒç›´è¿, type: direct, udp: true}
  - {name: DNS_Hijack, type: dns}
proxy-groups:
  - {name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©, type: select, proxies: [â™»ï¸ å»¶è¿Ÿæœ€ä½,ğŸŒ å…¨çƒç›´è¿], use: [All]}
  - {name: â™»ï¸ å»¶è¿Ÿæœ€ä½, type: url-test, url: https://www.google.com/generate_204, interval: 300, tolerance: 500, use: [All]}
  - {name: ğŸ“² ç”µæŠ¥ä¿¡æ¯, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ å»¶è¿Ÿæœ€ä½, ğŸŒ å…¨çƒç›´è¿], use: [All]}
  - {name: ğŸ¬ æ²¹ç®¡åª’ä½“, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ å»¶è¿Ÿæœ€ä½, ğŸŒ å…¨çƒç›´è¿], use: [All]}
  - {name: ğŸ“¸ TikTok, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ å»¶è¿Ÿæœ€ä½, ğŸŒ å…¨çƒç›´è¿], use: [All]}
  - {name: ğŸ“¹ å¥ˆé£åª’ä½“, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ å»¶è¿Ÿæœ€ä½, ğŸŒ å…¨çƒç›´è¿], use: [All]}
  - {name: ğŸ“¢ è°·æ­ŒæœåŠ¡, type: select, proxies: [ğŸŒ å…¨çƒç›´è¿,  ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ å»¶è¿Ÿæœ€ä½], use: [All]}
  - {name: â“‚ï¸ å¾®è½¯æœåŠ¡, type: select, proxies: [ğŸŒ å…¨çƒç›´è¿,  ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ å»¶è¿Ÿæœ€ä½], use: [All]}   
  - {name: ğŸ è‹¹æœæœåŠ¡, type: select, proxies: [ğŸŒ å…¨çƒç›´è¿,  ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ å»¶è¿Ÿæœ€ä½], use: [All]}
  - {name: ğŸ“º å“”å“©å“”å“©, type: select, proxies: [ğŸŒ å…¨çƒç›´è¿,  ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ å»¶è¿Ÿæœ€ä½], use: [All]}
  - {name: ğŸ¹ ç½‘æ˜“éŸ³ä¹, type: select, proxies: [ğŸŒ å…¨çƒç›´è¿,  ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ å»¶è¿Ÿæœ€ä½], use: [All]}
  - {name: ğŸ‡¨ğŸ‡³ ç›´è¿åŸŸå, type: select, proxies: [ğŸŒ å…¨çƒç›´è¿,  ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ å»¶è¿Ÿæœ€ä½], use: [All]}
  - {name: ğŸ‡¨ğŸ‡³ ç›´è¿ IP, type: select, proxies: [ğŸŒ å…¨çƒç›´è¿,  ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ å»¶è¿Ÿæœ€ä½], use: [All]}
  - {name: ğŸ§± ä»£ç†åŸŸå, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ å»¶è¿Ÿæœ€ä½, ğŸŒ å…¨çƒç›´è¿], use: [All]}
  - {name: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª, type: select, proxies: [REJECT, ğŸŒ å…¨çƒç›´è¿]}
  - {name: ğŸ‹ æ¼ç½‘ä¹‹é±¼, type: select, proxies: [ ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ å»¶è¿Ÿæœ€ä½, ğŸŒ å…¨çƒç›´è¿]}

  #############################################################################################################################
  
  

# ç¬¬ä¸‰éƒ¨åˆ† è§„åˆ™é…ç½®  
# è§„åˆ™æä¾›è€…åœ¨ä¸‹
rule-providers: # https://github.com/Loyalsoldier/clash-rules é¡¹ç›®åœ°å€    å¦å¤–ä¸€ä¸ªè§„åˆ™åº“https://rules.xkww3n.cyou/   å°†åœ¨ä»¥åæ·»åŠ 
  telegramip:
    type: http
    behavior: ipcidr
    format: mrs
    path: ./ruleset/telegramip.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/telegramip.mrs"
    interval: 86400

  youtube:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/youtube.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/youtube.mrs"
    interval: 86400

  tiktok:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/tiktok.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/tiktok.mrs"
    interval: 86400

  netflix:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/netflix.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/netflix.mrs"
    interval: 86400

  netflixip:
    type: http
    behavior: ipcidr
    format: mrs
    path: ./ruleset/netflixip.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/netflixip.mrs"
    interval: 86400

  google-cn:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/google-cn.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/google-cn.mrs"
    interval: 86400

  bilibili:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/bilibili.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/bilibili.mrs"
    interval: 86400

  microsoft-cn:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/microsoft-cn.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/microsoft-cn.mrs"
    interval: 86400

  apple-cn:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/apple-cn.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/apple-cn.mrs"
    interval: 86400

  cn:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/cn.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/cn.mrs"
    interval: 86400

  cnip:
    type: http
    behavior: ipcidr
    format: mrs
    path: ./ruleset/cnip.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/cnip.mrs"
    interval: 86400

  proxy:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/proxy.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/proxy.mrs"
    interval: 86400

  ads:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/ads.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/ads.mrs"
    interval: 86400


rules:
  # åŸºæœ¬è§„åˆ™
  - GEOSITE,private,DIRECT   # ä¸»æµ Clash dashboard åœ¨çº¿é¢æ¿åŸŸå
  ## fix dnsleak
  - IP-CIDR,127.0.0.1/32,REJECT,no-resolve
  - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
  - IP-CIDR,28.0.0.1/8,REJECT,no-resolve
  - IP-CIDR6,::1/128,REJECT,no-resolve  
  ## direct FCM
  - AND,((NETWORK,TCP),(DST-PORT,5228-5230)),DIRECT
  - AND,((NETWORK,TCP),(DST-PORT,5228-5230),(OR,((DOMAIN-KEYWORD,google)))),DIRECT
  ## direct ntp
  - AND,((NETWORK,UDP),(DST-PORT,123)),DIRECT
  - DST-PORT,123/136/137-139,DIRECT,udp

  - DST-PORT,53,DNS_Hijack
  - AND,((PROCESS-NAME,mihomo),(NOT,((IN-TYPE,inner)))),REJECT
  - AND,((PROCESS-NAME,clash),(NOT,((IN-TYPE,inner)))),REJECT

  - DOMAIN-SUFFIX,o33249.ingest.sentry.io,REJECT  # OPENAI è·Ÿè¸ªåŸŸå reject
  - DOMAIN-SUFFIX,openaicom.imgix.net,REJECT  # OPENAI è·Ÿè¸ªåŸŸå reject


  # è‡ªå®šä¹‰è§„åˆ™ é«˜ä¼˜å…ˆåº¦
  # geosite åŒ…å«ï¼šfakeip-filter/private/ads/microsoft-cn/apple-cn/google-cn/games-cn/netflix/disney/max/primevideo/appletv/youtube/tiktok/bilibili/ai/networktest/proxy/cn
  - RULE-SET,ads,ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
  - PROCESS-NAME,com.netease.cloudmusic,ğŸ¹ ç½‘æ˜“éŸ³ä¹

  - RULE-SET,netflix,ğŸ“¹ å¥ˆé£åª’ä½“
  - RULE-SET,microsoft-cn,â“‚ï¸ å¾®è½¯æœåŠ¡
  - RULE-SET,apple-cn,ğŸ è‹¹æœæœåŠ¡ 
  - RULE-SET,google-cn,ğŸ“¢ è°·æ­ŒæœåŠ¡
  - RULE-SET,youtube,ğŸ¬ æ²¹ç®¡åª’ä½“
  - RULE-SET,tiktok,ğŸ“¸ TikTok
  - RULE-SET,bilibili,ğŸ“º å“”å“©å“”å“©

  - RULE-SET,proxy,ğŸ§± ä»£ç†åŸŸå
  - RULE-SET,cn,ğŸ‡¨ğŸ‡³ ç›´è¿åŸŸå
  - RULE-SET,netflixip,ğŸ“¹ å¥ˆé£åª’ä½“,no-resolve
  - RULE-SET,telegramip,ğŸ“² ç”µæŠ¥ä¿¡æ¯,no-resolve
  - RULE-SET,cnip,ğŸ‡¨ğŸ‡³ ç›´è¿ IP

  # ä½ä¼˜å…ˆåº¦ åŒ¹é…Â·æ¼ç½‘ä¹‹é±¼               
  - MATCH,ğŸ‹ æ¼ç½‘ä¹‹é±¼ # æ”¶å°¾
